sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala
scala:
  - 2.12.10
  - 2.13.0

jdk:
  - openjdk8

script:
  - sbt -Dmacro.scala.version=$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -Dquill.macro.log=false -Dquill.binds.log=true clean coverage test coverageReport scalastyle
  - sbt -Dmacro.scala.version=$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
  - sbt -Dmacro.scala.version=$TRAVIS_SCALA_VERSION coveralls
   # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm -f
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm -f


