package pl.jozwik.quillgeneric.sync

class H2AbstractQuillCrudH2Spec extends PersonRepositoryNotGeneratedIdSuite
  with PersonCustomRepositorySuite
  with PersonRepositorySuite
  with ConfigurationRepositorySuite