CREATE TABLE IF NOT EXISTS ADDRESS
(
    ID         INT         NOT NULL AUTO_INCREMENT,
    COUNTRY VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STREET VARCHAR(50)  DEFAULT NULL,
    BUILDING_NUMBER VARCHAR(10)  DEFAULT NULL,
    LOCAL_NUMBER VARCHAR(10)  DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS PERSON
(
    ID         INT         NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME  VARCHAR(20) NOT NULL,
    BIRTH_DATE DATE,
    ADDRESS_ID INT DEFAULT NULL
);


CREATE TABLE IF NOT EXISTS PERSON2
(
    ID         INT         NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME  VARCHAR(20) NOT NULL,
    BIRTH_DATE DATE,
    ADDRESS_ID INT DEFAULT NULL
);
