CREATE TABLE IF NOT EXISTS PERSON
(
    ID         INT         NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME  VARCHAR(20) NOT NULL,
    BIRTH_DATE DATE
);


CREATE TABLE IF NOT EXISTS PERSON2
(
    ID         INT         NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME  VARCHAR(20) NOT NULL,
    BIRTH_DATE DATE
);
